### ISSUE TITLE
Add SKU as metadata to all product event IDs in the activity log

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#114]
More often than not, a product in WooCommerce will have a SKU.

I think it is a good idea to add the product's SKU to all events in which we report a product. However, can this be dynamic, i.e. not report it if there is no SKU? Or we simply report N/A.

Thoughts?

**Comment by DannyWPWS** [comment]
I think we can safely do this for all "WooCommerce Product" events which are as follows:

9000, 9001, 9003, 9004, 9005, 9006, 9007, 9008, 9009, 9010, 9012, 9013, 9014, 9015, 9072, 9073, 9077, 9095, 9096, 9097, 9098,9099

Adding a new metadata row 

Product SKU: %SKU%

Which will show either the SKU or "None supplied" if we cant find one would work

**Comment by DannyWPWS** [comment]
Iv updated the event sheet to suit :)

**Comment by robert81** [comment]
Thanks @DannyWPWS .

Just to confirm, we should add it to each event where there is the Product ID as part of the metadata.
