### ISSUE TITLE
New event ID 9119 for Stock Treshold

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#118]
Please add event ID 9119 - [Event IDs reference](https://docs.google.com/spreadsheets/d/1xjO3E7GtsOMPHTfLyaurNeJqmJkRCRsleBSAhsicyXA/edit#gid=1446535160)

For this setting in a WooCommerce product:

![image](https://user-images.githubusercontent.com/3965050/153348069-a61c5e93-48d8-4fb5-bffe-d69fde9b3cfb.png)

**Comment by DannyWPWS** [comment]
Fixed in this PR https://github.com/wpwhitesecurity/wsal-woocommerce/pull/129
