### ISSUE TITLE
Improved coverage of order changes

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#121]
Right now, we only have event ID 9040 for when an order has changed. We need to add more, using event IDs 9120+. We need events for when an agent reviewing the order can:

1) Add / remove a product from the order
2) Change the quantity of a product in an order
3) Adds / removes / changes a fee
4) Adds / removes a coupon
5) Adds . removes tax

Even ID 9040 should be reported when there is a change that is not covered by any specific change, like the ones above.

**Comment by DannyWPWS** [comment]
@robert81 9120 has been taken by some new webhook events: https://github.com/wpwhitesecurity/wsal-woocommerce/issues/89

https://docs.google.com/spreadsheets/d/1xjO3E7GtsOMPHTfLyaurNeJqmJkRCRsleBSAhsicyXA/edit?pli=1#gid=1446535160

So for now ill go with 9130+ and we can change this if needed

**Comment by DannyWPWS** [comment]
9130 - Added/removed an item
9131 - Quantity changed
