### ISSUE TITLE
Improve event ID 9041 by reporting more details

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#125]
At the moment, when a user refunds an order, we only show the order title. Example:

Refunded the order %OrderTitle%.

We need to add more info to this event ID, mainly the user who placed the order. The question though is what is the difference between having a registered users VS non registered?

In some cases shops allow users to register a user, which means there will be a user on the website, in some others not. So can we report the user who placed the order, and if the user who placed the order is registered we link the username?

Let's see what is possible, what options we have and finalize the details once we know what we can and cannot do. Once we update this we also need to update the [List of Event IDs document](https://docs.google.com/spreadsheets/d/1xjO3E7GtsOMPHTfLyaurNeJqmJkRCRsleBSAhsicyXA/edit#gid=1446535160)

**Comment by DannyWPWS** [comment]
Ok username was nice and easy - we have the customer username if applicable, or we report "Guest" which is how WC reports its in the order edit screen

![image](https://user-images.githubusercontent.com/59394454/160821852-fe73c4bf-9c53-4e61-b5d4-3064533e503d.png)

![image](https://user-images.githubusercontent.com/59394454/160821980-65d54fc3-0046-4970-be57-d61f71993064.png)

Maybe add the order created date too? 

![image](https://user-images.githubusercontent.com/59394454/160821919-c8684a13-3733-4baa-94a3-c7711198ad35.png)

**Comment by DannyWPWS** [comment]
I like it! 

![image](https://user-images.githubusercontent.com/59394454/160823077-08c43d4e-81d6-4f18-92c6-3364013470f0.png)

**Comment by DannyWPWS** [comment]
Adding refunded amount and also refund reason :)

**Comment by DannyWPWS** [comment]
Looks good, threw the correct currency in there too as it looked weird without it

![image](https://user-images.githubusercontent.com/59394454/160839941-739fe259-2803-4199-b603-5d44a57fec96.png)
