### ISSUE TITLE
PHP error when editing payment methods / product variations etc

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#142]
Issue reported here: https://wordpress.org/support/topic/conflict-with-woocommerce-101/

I could easily reproduce it.

**Comment by DannyWPWS** [comment]
Closing this up, reported here https://github.com/wpwhitesecurity/wsal-woocommerce/issues/137 and fixed here https://github.com/wpwhitesecurity/wsal-woocommerce/commit/7df892c11535aec57dc99ebdafbc351922c42ee5
