### ISSUE TITLE
Not all Product event IDs have got the Product SKU metadata

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#148]
For example, event ID 9019 does not have the Product SKU:

![image](https://user-images.githubusercontent.com/3965050/161600956-e41daf3d-2da2-4cd8-b2e7-2f114290f637.png)

Let's check all the event IDs where the product is mentioned. I think all products with the object **WooCommerce Product** can have this.

**Comment by DannyWPWS** [comment]
Closing, fixed here https://github.com/wpwhitesecurity/wsal-woocommerce/pull/154
