### ISSUE TITLE
Event ID 9130 (added product to order) reported after event ID 9035 (order was placed)

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#150]
![image](https://user-images.githubusercontent.com/3965050/161601776-73b05786-aad4-4a88-a479-84d73d201e82.png)

When a user places an order, obviously the product(s) are added to the order. However, reporting these two events after each other when an order is placed it will confuse the user. When a product is added to an order due to a purchase, event 9130 should not be reported.

**Comment by DannyWPWS** [comment]
Closing, fixed here https://github.com/wpwhitesecurity/wsal-woocommerce/pull/154
