### ISSUE TITLE
Error when changing "anything" in an order

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#151]
I tried changing the product quantity in an order and the interface crashed:

![image](https://user-images.githubusercontent.com/3965050/161602289-af58fc92-8aca-4402-857d-940e4f0378d0.png)

Then the same error was logged in the debug log file as the error reported in issue #149 

Here it is just in case:

[04-Apr-2022 17:49:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WSAL_Sensors_WooCommerce_Public::get_product_sku() in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:360
Stack trace:
#0 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/class-wp-hook.php(307): WSAL_Sensors_WooCommerce_Public->product_stock_changed()
#1 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(63): do_action()
#4 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(237): wc_upd in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/wsal/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php on line 360

**Note:** this is happening whenever I add / remove something from the order, such as a shipping method, fee etc.

**Comment by DannyWPWS** [comment]
Closing, fixed here https://github.com/wpwhitesecurity/wsal-woocommerce/pull/154
