### ISSUE TITLE
Event ID 9040 (changed order details) reported after event ID 9137 (added shipping in order)

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#153]
![image](https://user-images.githubusercontent.com/3965050/161604241-3ca6972d-5580-4629-a9df-e2bb576a884a.png)

I do not know if this is happening because of the bug reported in other issues or just default behaviour, also I do not know if it also happens after event IDs reporting all other order details changes (such as product quantity, shipping, fees etc), but event ID 9040 shuold not be reported after an event which is logged due to a change in an order.

**Comment by DannyWPWS** [comment]
Just a note on how this works:

When you add/remove a product/shipping/tax etc to an order, the order itself is immediately updated and saved without the need for the user to click "update" and we report the event as normal

If, within 20 seconds of the item being added/removed etc the user clicks "update" for whatever reason, we currently suppress 9040 to avoid confusing alerts, after 20 seconds 9040 can resume and will currently appear whenever the order is updated.

Note, we will be altering the vaugness of 9040 here https://github.com/wpwhitesecurity/wsal-woocommerce/issues/155

**Comment by DannyWPWS** [comment]
Closing, fixed here https://github.com/wpwhitesecurity/wsal-woocommerce/pull/154
