### ISSUE TITLE
Event ID 2100 reported when user opens an order

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#157]
When I open an order on WooCommerce, this event is reported, which is seeing / reporting the order as a post:

![image](https://user-images.githubusercontent.com/3965050/161827612-bbd763cb-f056-46ec-ba87-dccf101d265c.png)

At the moment we do not have any event IDs for when a user opens an order, but it is something we should create now as well.

**Comment by DannyWPWS** [comment]
New event 9154 has been added to the sheet

**Comment by DannyWPWS** [comment]
![image](https://user-images.githubusercontent.com/59394454/201644652-2b450fc3-0de1-40e5-8407-2544299581b9.png)
