### ISSUE TITLE
6648 - Product price changes via Smart Manager are not logged

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#194]
The user for whom we've done the price monitoring changes uses another plugin to do price changes: https://wordpress.org/plugins/smart-manager-for-wp-e-commerce/

He said that the price changes done via this plugin are not recorded. Can you please test it and advise? Let's see why it is not working - as usual if they are doing price changes in a non-standard way we should not be bothered. So let's check that first and then let me know.

**Comment by DannyWPWS** [comment]
Yikes, well unlike the other plugin - this one totally skips all WC stuff and makes changes directly to the post's data using things like wp_set_object_terms meaning the usual filters such as "woocommerce_after_product_object_save" (which we used for the last plugin) simply are not fired so we cant be aware

![image](https://user-images.githubusercontent.com/59394454/167588016-445ea006-5611-4a47-a765-4cd873440f4d.png)

**Comment by robert81** [comment]
Thanks @DannyWPWS for checking.
