### ISSUE TITLE
Deprecated Errors when trying to log in (2FA enabled)

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#211]
![ww](https://user-images.githubusercontent.com/92275653/200836881-233d5122-9270-4490-b364-efb095b5c278.png)
Got the following errors just after I tried to log in using the woocomerce login dashboard.(my-account). 
This ocured on the 2FA dashboard since I had it on, but It did not happen every time, I managed to capture it twice today (still trying to figure out why/how, but maybe you guys can figure it out if it's a problem)

After I disabled 2FA for this test user, the error disasppeared. 

log file is here 
[debug.log](https://github.com/wpwhitesecurity/wsal-woocommerce/files/9971274/debug.log)

**Comment by DannyWPWS** [comment]
If anything, I think this is an issue for WP 2FA's repo and see you have opened an issue here https://github.com/wpwhitesecurity/wp-2fa-premium/issues/1407 so ill close this up as there is nothing to do within this extension for it
