### ISSUE TITLE
ID 4015/4016 showing up instead of 1000 when logging in WC page

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#225]
https://files.fm/u/dzw9hp4zt

Basically log ins are not being captured with the correct ID 1000 when trying to log in using the /my-account page but instead ID 4015 and 4016. Also, instead of the username, 'System" is displayed. Expected?

On the other hand, log outs are correctly captured as 1001.

This reproduces as well when trying to log in using the /wp-admin login page.

**Comment by DannyWPWS** [comment]
@jwjsystem Can you confirm if you had front end logins enabled under WP Activity Log > Enable/Disable Events?

![image](https://user-images.githubusercontent.com/59394454/201927708-5db78e13-6949-463e-828c-4fe8c4b65c0f.png)

Regarding 'system' - id say thats correct as its not a value the user has purposfully intervened with, its something occurring under the hood

**Comment by DannyWPWS** [comment]
Closing this up, issue opened here https://github.com/wpwhitesecurity/wp-security-audit-log-premium/issues/2852
