### ISSUE TITLE
4.4.2.2 - Event ID 2101s are showing up when changing shipping/billing address

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#232]
![ww](https://user-images.githubusercontent.com/92275653/201962823-d57f7ff4-f804-46a0-81c3-63c74535c0c1.png)

I've used a 'customer' role user, with no dashboard acces into the WP site.

Lots of 2101 events showed up after adding shipping  and billing addresses from the Account Dashboard of WC on the front end of the website. 
**Mention:**  I've added data in all input fields once for shipping and once for billing , but there are lots of 2101 events that showed up.

**Expected result:** 
9084 and 9083 were my expectation in terms of event IDs that should have showed up.

**Comment by DannyWPWS** [comment]
This is a fix within WSAL itself (its working with current develop) - cant retroactivly ammend this so as its not causing errors ill close this up - I have opened this one which this issue has led too however - https://github.com/wpwhitesecurity/wsal-woocommerce/issues/236
