### ISSUE TITLE
(edge case) Fatal error E_error when disabling WooCommerce plugin

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#260]
After disabling the WC plugin - the fatal error was introduced. I know that the plugin extension is highly dependent to the WooCommerce plugin and needs it to be active - but there is anything we can do about this?

Might be an edge case, but maybe we can do something about it since some developers might encounter this during troubleshooting sessions, or when upgrading the plugin on staging websites etc

```
Error Details
=============
An error of type E_ERROR was caused in line 328 of the file /var/www/[lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php](http://lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php). Error message: Uncaught Error: Call to undefined function WSAL\Plugin_Sensors\wc_get_order() in /var/www/[lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:328](http://lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:328)
Stack trace:
#0 /var/www/[lucian.wpws.org/site4/wp-includes/class-wp-hook.php(308)](http://lucian.wpws.org/site4/wp-includes/class-wp-hook.php(308)): WSAL\Plugin_Sensors\WooCommerce_Sensor::order_opened_for_editing()
#1 /var/www/[lucian.wpws.org/site4/wp-includes/class-wp-hook.php(332)](http://lucian.wpws.org/site4/wp-includes/class-wp-hook.php(332)): WP_Hook->apply_filters()
#2 /var/www/[lucian.wpws.org/site4/wp-includes/plugin.php(517)](http://lucian.wpws.org/site4/wp-includes/plugin.php(517)): WP_Hook->do_action()
#3 /var/www/[lucian.wpws.org/site4/wp-admin/admin.php(419)](http://lucian.wpws.org/site4/wp-admin/admin.php(419)): do_action()
#4 /var/www/[lucian.wpws.org/site4/wp-admin/post.php(12)](http://lucian.wpws.org/site4/wp-admin/post.php(12)): require_once('/var/www/lucian...')
#5 {main}
  thrown
```
**Also this pops up in the emails of course:** 
![www](https://user-images.githubusercontent.com/92275653/236152077-1a26f947-3c35-4b40-b06b-bb9877678dd3.png)

The error also occurs when updating the extension and the WooCommerce plugin is disabled (just tested by re-installing the current WC extension build, with the WooCommerce plugin disabled)

`Fatal error: Uncaught Error: Call to undefined function WSAL\Plugin_Sensors\wc_get_order() in /var/www/lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:1420 Stack trace: #0 /var/www/lucian.wpws.org/site4/wp-includes/class-wp-hook.php(310): WSAL\Plugin_Sensors\WooCommerce_Sensor::event_deleted() #1 /var/www/lucian.wpws.org/site4/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /var/www/lucian.wpws.org/site4/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /var/www/lucian.wpws.org/site4/wp-includes/post.php(6383): do_action() #4 /var/www/lucian.wpws.org/site4/wp-admin/includes/class-file-upload-upgrader.php(126): wp_delete_attachment() #5 /var/www/lucian.wpws.org/site4/wp-admin/update.php(179): File_Upload_Upgrader->cleanup() #6 {main} thrown in /var/www/lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php on line 1420`

**Comment by sdobreff** [comment]
I can not reproduce that, so ill blindly implement some solution and hope for the best
